package com.releasepilot.promotion.domain;

public enum DomainErrorCode {
    INVALID_ENVIRONMENT,
    ENVIRONMENT_SKIPPED,
    PREVIOUS_ENVIRONMENT_INCOMPLETE,
    PROMOTION_ALREADY_IN_PROGRESS,
    INVALID_PROMOTION_STATE,
    PROMOTION_IMMUTABLE,
    APPROVER_REQUIRED,
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS
}
